{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "53a12743",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Imports\n",
    "\n",
    "from dataclasses import dataclass\n",
    "\n",
    "import cadquery as cq\n",
    "\n",
    "# from jupyter_cadquery import show\n",
    "from ocp_vscode import show\n",
    "# from tools import show"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "0dcb3a10",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Dims\n",
    "\n",
    "\n",
    "@dataclass\n",
    "class MeasuredDims:\n",
    "    tap_pipe_diameter: float = 44.7\n",
    "    tap_to_sink_edge_distance: float = 33.1\n",
    "    tap_control_to_slab_dist = 40.5\n",
    "    tap_control_diameter = 50.0\n",
    "\n",
    "\n",
    "md = MeasuredDims()\n",
    "\n",
    "\n",
    "@dataclass\n",
    "class DripDims:\n",
    "    # The thickness of the \"floor\" of the dripper\n",
    "    base_thickness: float = 0.6\n",
    "\n",
    "    # The distance the dripper should extend over the edge of the sink\n",
    "    extrusion_depth: float = 5\n",
    "\n",
    "    length: float = 180  # x axis length\n",
    "    depth: float = 190  # y axis length\n",
    "    wall_height: float = 3\n",
    "    wall_thickness: float = 0.8\n",
    "\n",
    "    pipe_envelope_height: float = 12\n",
    "    angle: float = 3  # degs\n",
    "\n",
    "    tap_pip_features_center_y_axis = (\n",
    "        extrusion_depth + md.tap_to_sink_edge_distance + md.tap_pipe_diameter / 2\n",
    "    )\n",
    "\n",
    "\n",
    "@dataclass\n",
    "class AuxDripperDims:\n",
    "    width: float = 80\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "e112404c",
   "metadata": {},
   "outputs": [],
   "source": [
    "def make_dripper(width: float) -> cq.Workplane:\n",
    "    d = DripDims()\n",
    "\n",
    "    base = (\n",
    "        cq.Workplane(\"XY\")\n",
    "        .rect(width, d.depth + d.extrusion_depth, centered=False)\n",
    "        .extrude(d.base_thickness + d.wall_height)\n",
    "    )\n",
    "\n",
    "    main_body_hole = (\n",
    "        cq.Workplane(\"XY\")\n",
    "        .rect(width - 2 * d.wall_thickness, d.depth - d.wall_thickness, centered=False)\n",
    "        .extrude(d.wall_height)\n",
    "        .translate((d.wall_thickness, d.extrusion_depth, d.base_thickness))\n",
    "    )\n",
    "\n",
    "    extrusion_hole = (\n",
    "        cq.Workplane(\"XY\")\n",
    "        .rect(width, d.extrusion_depth, centered=False)\n",
    "        .extrude(d.wall_height)\n",
    "        .translate((0, 0, d.base_thickness))\n",
    "    )\n",
    "\n",
    "    return base - main_body_hole - extrusion_hole\n",
    "\n",
    "\n",
    "def make_pipe_envelope() -> cq.Workplane:\n",
    "    d = DripDims()\n",
    "    md = MeasuredDims()\n",
    "\n",
    "    return (\n",
    "        cq.Workplane(\"XY\")\n",
    "        .moveTo(0, d.tap_pip_features_center_y_axis)\n",
    "        .circle((md.tap_pipe_diameter / 2) + d.wall_thickness)\n",
    "        .extrude(d.pipe_envelope_height)\n",
    "        .rotate(\n",
    "            (-1, md.tap_to_sink_edge_distance + d.extrusion_depth, 0),\n",
    "            (1, md.tap_to_sink_edge_distance + d.extrusion_depth, 0),\n",
    "            -d.angle,\n",
    "        )\n",
    "        .translate((0, 0, -2))\n",
    "    )\n",
    "\n",
    "\n",
    "def make_pipe_hole() -> cq.Workplane:\n",
    "    d = DripDims()\n",
    "    md = MeasuredDims()\n",
    "\n",
    "    return (\n",
    "        cq.Workplane(\"XY\")\n",
    "        .moveTo(0, d.tap_pip_features_center_y_axis)\n",
    "        .circle((md.tap_pipe_diameter / 2))\n",
    "        .extrude(d.pipe_envelope_height * 2)\n",
    "        .rotate(\n",
    "            (-1, md.tap_to_sink_edge_distance + d.wall_thickness + d.extrusion_depth, 0),\n",
    "            (1, md.tap_to_sink_edge_distance + d.wall_thickness + d.extrusion_depth, 0),\n",
    "            -d.angle,\n",
    "        )\n",
    "        .translate((0, 0, -5))\n",
    "    )\n",
    "\n",
    "\n",
    "def make_main_dripper() -> cq.Workplane:\n",
    "    d = DripDims()\n",
    "    md = MeasuredDims()\n",
    "    dripper = make_dripper(d.length)\n",
    "    pipe_envelope = make_pipe_envelope()\n",
    "    pipe_hole = make_pipe_hole()\n",
    "\n",
    "    left_edge_cut_off = (\n",
    "        cq.Workplane(\"XY\").rect(100, 100, centered=False).extrude(100).translate((-100, 0, 0))\n",
    "    )\n",
    "    base_cut_off = (\n",
    "        cq.Workplane(\"XY\").rect(500, 500, centered=False).extrude(100).translate((-100, 0, -100))\n",
    "    )\n",
    "\n",
    "    all = dripper + pipe_envelope - pipe_hole - left_edge_cut_off - base_cut_off\n",
    "    return all\n",
    "\n",
    "\n",
    "main_dripper = make_main_dripper()\n",
    "_ = main_dripper.export(\"main_dripper.stl\")\n",
    "# _ = show(main_dripper)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "69f8b83e-9439-455b-83ee-a0d7dcbebbcf",
   "metadata": {
    "editable": true,
    "slideshow": {
     "slide_type": ""
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "def make_auxiliary_dripper():\n",
    "    d = AuxDripperDims()\n",
    "    dripper = make_dripper(d.width)\n",
    "    pipe_envelope = make_pipe_envelope().translate((d.width, 0, 0))\n",
    "    pipe_hole = make_pipe_hole().translate((d.width, 0, 0))\n",
    "    right_edge_cut_off = (\n",
    "        cq.Workplane(\"XY\").rect(100, 100, centered=False).extrude(100).translate((d.width, 0, 0))\n",
    "    )\n",
    "\n",
    "    base_cut_off = (\n",
    "        cq.Workplane(\"XY\").rect(500, 500, centered=False).extrude(100).translate((-100, 0, -100))\n",
    "    )\n",
    "\n",
    "    all = dripper + pipe_envelope - pipe_hole - right_edge_cut_off - base_cut_off\n",
    "\n",
    "    return all\n",
    "\n",
    "\n",
    "aux_dripper = make_auxiliary_dripper()\n",
    "_ = aux_dripper.export(\"aux_dripper.stl\")\n",
    "# _ = show(aux_dripper)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "25b59160-ab83-4edf-bc9b-3cc21fb835a6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ccccc\n"
     ]
    }
   ],
   "source": [
    "def make_assembly():\n",
    "    d = DripDims()\n",
    "    md = MeasuredDims()\n",
    "    ad = AuxDripperDims()\n",
    "    primary = make_main_dripper()\n",
    "    aux = make_auxiliary_dripper()\n",
    "\n",
    "    slab_thickness = 50.0\n",
    "    slab_w = 400.0\n",
    "    slab_d = 300.0\n",
    "\n",
    "    slab = cq.Workplane(\"XY\").rect(slab_w, slab_d, centered=False).extrude(slab_thickness)\n",
    "    tap_pipe = (\n",
    "        cq.Workplane(\"XY\")\n",
    "        # .moveTo(100, md.tap_to_sink_edge_distance + md.tap_pipe_diameter / 2)\n",
    "        .circle(md.tap_pipe_diameter / 2)\n",
    "        .extrude(80)\n",
    "    )\n",
    "\n",
    "    tap_ctrl_pip = cq.Workplane(\"YZ\").circle(md.tap_control_diameter / 2).extrude(80)\n",
    "    ass = cq.Assembly()\n",
    "    ass.add(slab, color=cq.Color(\"white\"))\n",
    "    ass.add(\n",
    "        tap_pipe,\n",
    "        color=cq.Color(\"gray\"),\n",
    "        loc=cq.Location(\n",
    "            (slab_w / 2, md.tap_to_sink_edge_distance + md.tap_pipe_diameter / 2, slab_thickness)\n",
    "        ),\n",
    "    )\n",
    "    ass.add(\n",
    "        tap_ctrl_pip,\n",
    "        color=cq.Color(\"gray\"),\n",
    "        loc=cq.Location(\n",
    "            (\n",
    "                slab_w / 2 - md.tap_pipe_diameter / 2 - 20,\n",
    "                md.tap_to_sink_edge_distance + md.tap_control_diameter / 2,\n",
    "                slab_thickness + md.tap_control_to_slab_dist,\n",
    "            )\n",
    "        ),\n",
    "    )\n",
    "\n",
    "    primary = primary.rotate((-1, d.extrusion_depth, 0), (1, d.extrusion_depth, 0), d.angle)\n",
    "    ass.add(\n",
    "        primary,\n",
    "        loc=cq.Location((slab_w / 2, -d.extrusion_depth, slab_thickness)),\n",
    "    )\n",
    "\n",
    "    aux = make_auxiliary_dripper().rotate(\n",
    "        (-1, d.extrusion_depth, 0), (1, d.extrusion_depth, 0), d.angle\n",
    "    )\n",
    "    ass.add(\n",
    "        aux,\n",
    "        loc=cq.Location((slab_w / 2 - ad.width, -d.extrusion_depth, slab_thickness)),\n",
    "    )\n",
    "\n",
    "    return ass\n",
    "\n",
    "\n",
    "_ = show(make_assembly())"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "3dprinting-design",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
